// Generated by CoffeeScript 1.6.3
var Catalog, Chain, EventEmitter, MODES, Replay, logger, passThrough, passToLocalhost, passWhenBloodyOrCheat, recorder, replay,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __slice = [].slice;

Catalog = require("./catalog");

Chain = require("./chain");

EventEmitter = require("events").EventEmitter;

logger = require("./logger");

passThrough = require("./pass_through");

recorder = require("./recorder");

MODES = ["bloody", "cheat", "record", "replay"];

Replay = (function(_super) {
  __extends(Replay, _super);

  function Replay(mode) {
    var _this = this;
    if (!~MODES.indexOf(mode)) {
      throw new Error("Unsupported mode '" + mode + "', must be one of " + (MODES.join(", ")) + ".");
    }
    this.chain = new Chain();
    this.debug = !!process.env.DEBUG;
    this.fixtures = null;
    this.logger = {
      log: function(message) {
        if (_this.debug) {
          return console.log(message);
        }
      },
      error: function(message) {
        if (_this.debug || !_this.silent) {
          return console.error(message);
        }
      }
    };
    this.mode = mode;
    this._localhosts = {
      localhost: true
    };
    this._allowed = {};
    this._ignored = {};
    this.catalog = new Catalog(this);
    this.on("error", function(error, url) {
      return _this.logger.error("Replay: " + (error.message || error));
    });
  }

  Replay.prototype.use = function(proxy) {
    return this.chain.prepend(proxy);
  };

  Replay.prototype.allow = function() {
    var host, hosts, _i, _len, _results;
    hosts = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    _results = [];
    for (_i = 0, _len = hosts.length; _i < _len; _i++) {
      host = hosts[_i];
      this._allowed[host] = true;
      delete this._ignored[host];
      _results.push(delete this._localhosts[host]);
    }
    return _results;
  };

  Replay.prototype.isAllowed = function(host) {
    return !!this._allowed[host];
  };

  Replay.prototype.ignore = function() {
    var host, hosts, _i, _len, _results;
    hosts = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    _results = [];
    for (_i = 0, _len = hosts.length; _i < _len; _i++) {
      host = hosts[_i];
      this._ignored[host] = true;
      delete this._allowed[host];
      _results.push(delete this._localhosts[host]);
    }
    return _results;
  };

  Replay.prototype.isIgnored = function(host) {
    return !!this._ignored[host];
  };

  Replay.prototype.localhost = function() {
    var host, hosts, _i, _len, _results;
    hosts = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    _results = [];
    for (_i = 0, _len = hosts.length; _i < _len; _i++) {
      host = hosts[_i];
      this._localhosts[host] = true;
      delete this._allowed[host];
      _results.push(delete this._ignored[host]);
    }
    return _results;
  };

  Replay.prototype.isLocalhost = function(host) {
    return !!this._localhosts[host];
  };

  return Replay;

})(EventEmitter);

replay = new Replay(process.env.REPLAY || "replay");

passWhenBloodyOrCheat = function(request) {
  return replay.isAllowed(request.url.hostname) || (replay.mode === "cheat" && !replay.isIgnored(request.url.hostname));
};

passToLocalhost = function(request) {
  return replay.isLocalhost(request.url.hostname) || replay.mode === "bloody";
};

replay.use(passThrough(passWhenBloodyOrCheat));

replay.use(recorder(replay));

replay.use(logger(replay));

replay.use(passThrough(passToLocalhost));

module.exports = replay;
